/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Home: typeof import('./../src/components/home.vue')['default']
    NavigationDrawer: typeof import('./../src/components/layout/navigation-drawer.vue')['default']
    NavigationDrawerItems: typeof import('./../src/components/layout/navigation-drawer-items.vue')['default']
    Operation: typeof import('./../src/components/operation.vue')['default']
    OperationPannelRight: typeof import('./../src/components/operation-pannel-right.vue')['default']
    Prism: typeof import('./../src/components/prism.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SchemaViewer: typeof import('./../src/components/schema-viewer.vue')['default']
    Snippet: typeof import('./../src/components/snippet.vue')['default']
    TopBar: typeof import('./../src/components/layout/top-bar.vue')['default']
  }
}
