openapi: 3.1.0
info:
  title: API avec Référence Récursive
  description: Exemple d'API avec une référence récursive dans le schéma.
  version: 1.0.0
paths:
  /items:
    get:
      summary: Récupérer la liste des items
      responses:
        '200':
          description: Liste des items récupérée avec succès
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Item'
  /elems:
    get:
      summary: Récupérer la liste des éléments
      responses:
        '200':
          description: Liste des éléments récupérée avec succès
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Elem'
  
components:
  schemas:
    Item:
      type: object
      properties:
        id:
          type: string
          description: Identifiant unique de l'item
        name:
          type: string
          description: Nom de l'item
        parent:
          $ref: '#/components/schemas/Item'
      description: Schéma d'un item avec une référence récursive à lui-même
    Elem:
      type: object
      properties:
        id:
          type: string
          description: Identifiant unique de l'élément
        name:
          type: string
          description: Nom de l'élément
      description: Schéma d'un élément sans référence récursive